// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo0ZxPZfp-flZnW0iGDsZdiRwcaTV89bk',
    appId: '1:206575573221:web:ac5445508e6d2467fe5c0c',
    messagingSenderId: '206575573221',
    projectId: 'todo-c8f1c',
    authDomain: 'todo-c8f1c.firebaseapp.com',
    storageBucket: 'todo-c8f1c.appspot.com',
    measurementId: 'G-1QK5Y0DM9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABZA6E_Wemf-UWoEMB0ni-j1egseOQRcc',
    appId: '1:206575573221:android:1a58b9c149b68792fe5c0c',
    messagingSenderId: '206575573221',
    projectId: 'todo-c8f1c',
    storageBucket: 'todo-c8f1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH9JayHA9w8Lzi4D9zJGBxU8Vx1Bht800',
    appId: '1:206575573221:ios:49584551b301c10bfe5c0c',
    messagingSenderId: '206575573221',
    projectId: 'todo-c8f1c',
    storageBucket: 'todo-c8f1c.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH9JayHA9w8Lzi4D9zJGBxU8Vx1Bht800',
    appId: '1:206575573221:ios:49584551b301c10bfe5c0c',
    messagingSenderId: '206575573221',
    projectId: 'todo-c8f1c',
    storageBucket: 'todo-c8f1c.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo0ZxPZfp-flZnW0iGDsZdiRwcaTV89bk',
    appId: '1:206575573221:web:35b2b4bd513ce30ffe5c0c',
    messagingSenderId: '206575573221',
    projectId: 'todo-c8f1c',
    authDomain: 'todo-c8f1c.firebaseapp.com',
    storageBucket: 'todo-c8f1c.appspot.com',
    measurementId: 'G-X1TLZ7PM66',
  );
}
